File change

diff --git a/Modules/vOTUcluster_AllinOne b/Modules/vOTUcluster_AllinOne
--- a/Modules/vOTUcluster_AllinOne
+++ b/Modules/vOTUcluster_AllinOne
@@ -4,13 +4,13 @@
 start_time=$(date +%s)
 
 # 初始化变量
-INPUT_DIR=""
 RAW_SEQ_DIR=""
 OUTPUT_DIR=""
 DATABASE=""
 SAMPLETYPE=""
+ASSEMBLY_SOFTWARE=""
 REASSEMBLE=false
-VERSION="0.0.5"  # 定义版本号
+VERSION="0.0.6"  # 定义版本号
 CONCENTRATION_TYPE=""
 
 # 设置日志文件路径
@@ -19,10 +19,6 @@ LOG_FILE=""
 # 使用 getopts 处理短选项和手动处理长选项
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -i)
-      INPUT_DIR=$2
-      shift 2
-      ;;
     -r)
       RAW_SEQ_DIR=$2
       shift 2
@@ -38,6 +34,10 @@ while [[ $# -gt 0 ]]; do
       ;;
     -t) # 用 't' 代表 'type'
       SAMPLETYPE=$2
+      shift 2
+      ;;
+    -a) # 用 'a' 代表 'assembly software'
+      ASSEMBLY_SOFTWARE=$2
       shift 2
       ;;
     -v) # 显示版本信息
@@ -56,11 +56,11 @@ while [[ $# -gt 0 ]]; do
       echo "Usage: $0 [options]"
       echo ""
       echo "Options:"
-      echo "  -i <input_path_to_search>   Specify the input directory to search for FASTA files."
       echo "  -r <input_path_raw_seqs>    Specify the input directory to search for raw seqs files."
       echo "  -o <output_path>            Specify the output directory for the results."
       echo "  -d <database_path>          Specify the path to the database required for analysis."
       echo "  -t <sample_type>            Specify the sample type: DNA, RNA, or Mix."
+      echo "  -a <assembly_software>      Specify the assembly software: megahit, metaspades."
       echo "  --non-con                   Specify non-concentration processing."
       echo "  --con                       Specify concentration processing."
       echo "  --reassemble                Enable reassembly of bins."
@@ -80,8 +80,14 @@ while [[ $# -gt 0 ]]; do
 done
 
 # 检查必要的输入是否已提供
-if [ -z "$INPUT_DIR" ] || [ -z "$RAW_SEQ_DIR" ] || [ -z "$OUTPUT_DIR" ] || [ -z "$DATABASE" ] || [ -z "$SAMPLETYPE" ] || [ -z "$CONCENTRATION_TYPE" ]; then
-    echo "Usage: $0 -i <input_path_to_search> -r <input_path_raw_seqs> -o <output_path> -d <database_path> -t <sample_type> --non-con/--con [--reassemble]"
+if [ -z "$RAW_SEQ_DIR" ] || [ -z "$OUTPUT_DIR" ] || [ -z "$DATABASE" ] || [ -z "$SAMPLETYPE" ] || [ -z "$CONCENTRATION_TYPE" ] || [ -z "$ASSEMBLY_SOFTWARE" ]; then
+    echo "Usage: $0 -r <input_path_raw_seqs> -o <output_path> -d <database_path> -t <sample_type> -a <assembly_software> --non-con/--con [--reassemble]"
+    exit 1
+fi
+
+# 验证组装软件选项
+if [[ "$ASSEMBLY_SOFTWARE" != "megahit" && "$ASSEMBLY_SOFTWARE" != "metaspades" ]]; then
+    echo "Error: Invalid assembly software. Please choose either 'megahit' or 'metaspades'."
     exit 1
 fi
 
@@ -103,18 +109,6 @@ for FILE in "${RAW_SEQ_DIR}"/*_R1.*; do
     exit 1
   fi
 done
-
-# 根据 CONCENTRATION_TYPE 进行不同的处理
-if [ "$CONCENTRATION_TYPE" == "non-concentration" ]; then
-    echo "Running non-concentration specific steps..."
-    # 在这里添加 non-concentration 的特定处理步骤
-elif [ "$CONCENTRATION_TYPE" == "concentration" ]; then
-    echo "Running concentration specific steps..."
-    # 在这里添加 concentration 的特定处理步骤
-else
-    echo "Error: Invalid concentration type."
-    exit 1
-fi
 
 # 重定向所有输出到日志文件
 exec > >(tee -a "$LOG_FILE") 2>&1
@@ -139,6 +133,18 @@ esac
 # 输出选择的处理类型
 echo "Processing with $CONCENTRATION_TYPE mode."
 
+# 根据 CONCENTRATION_TYPE 进行不同的处理
+if [ "$CONCENTRATION_TYPE" == "non-concentration" ]; then
+    echo "Running non-concentration specific steps..."
+    # 在这里添加 non-concentration 的特定处理步骤
+elif [ "$CONCENTRATION_TYPE" == "concentration" ]; then
+    echo "Running concentration specific steps..."
+    # 在这里添加 concentration 的特定处理步骤
+else
+    echo "Error: Invalid concentration type."
+    exit 1
+fi
+
 # 获取当前 Conda 环境的 bin 文件夹位置
 if [ -z "$CONDA_PREFIX" ]; then
   echo "Conda environment is not activated."
@@ -147,7 +153,27 @@ fi
 ScriptDir="${CONDA_PREFIX}/bin"
 
 # 导出参数作为环境变量
-export INPUT_DIR OUTPUT_DIR DATABASE SAMPLETYPE REASSEMBLE
+export RAW_SEQ_DIR OUTPUT_DIR DATABASE SAMPLETYPE REASSEMBLE ASSEMBLY_SOFTWARE
+
+mkdir -p "${OUTPUT_DIR}/Log"
+#Raw sequence Process
+echo "Starting Raw sequences Process..."
+#Raw sequences module
+module_start_time=$(date +%s)
+Preprocess_module.sh "${RAW_SEQ_DIR}" "${ASSEMBLY_SOFTWARE}" "${OUTPUT_DIR}"> "${OUTPUT_DIR}/Log/Preprocess.log" 2>&1
+module_end_time=$(date +%s)
+module_runtime=$((module_end_time - module_start_time))
+echo "Viral prediction completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/Preprocess.log"
+
+
+# 导出参数作为环境变量
+CONTIGS_DIR="${OUTPUT_DIR}/Contigs"
+RAW_SEQ_DIR="${OUTPUT_DIR}/Cleanreads"
+INPUT_DIR=${CONTIGS_DIR}
+
+# 导出参数作为环境变量
+export INPUT_DIR OUTPUT_DIR DATABASE SAMPLETYPE REASSEMBLE ScriptDir RAW_SEQ_DIR
+
 
 # 过滤小于2000bp的序列
 mkdir -p "${OUTPUT_DIR}/FilteredSeqs"
@@ -158,11 +184,7 @@ FILES=$(find "${OUTPUT_DIR}/FilteredSeqs" -type f \( -name "*.fa" -o -name "*.fa
 RawFILES=$(find "${INPUT_DIR}" -maxdepth 1 -type f \( -name "*.fa" -o -name "*.fasta" \))
 
 # 导出必要的变量和函数
-export OUTPUT_DIR DATABASE Group FILES RawFILES CONCENTRATION_TYPE
-
-# 按顺序执行各个模块并记录时间和日志
-
-mkdir -p "${OUTPUT_DIR}/Log"
+export OUTPUT_DIR DATABASE Group FILES RawFILES CONCENTRATION_TYPE ScriptDir RAW_SEQ_DIR
 
 echo "Starting viral prediction..."
 #Viral prediction module
@@ -176,17 +198,27 @@ module_end_time=$(date +%s)
 module_runtime=$((module_end_time - module_start_time))
 echo "Viral prediction completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/viral_prediction.log"
 
-#Cross Validation module
+# Cross Validation module
 echo "Starting Cross Validation module..."
-module_start_time=$(date +%s)
-# 根据 CONCENTRATION_TYPE 进行不同的处理
-if [ "$CONCENTRATION_TYPE" == "non-concentration" ]; then
-    cross_validation_module.sh > "${OUTPUT_DIR}/Log/cross_validation.log" 2>&1
-else [ "$CONCENTRATION_TYPE" == "concentration" ]; then
-    cross_validation_module.sh > "${OUTPUT_DIR}/Log/cross_validation.log" 2>&1
-module_end_time=$(date +%s)
-module_runtime=$((module_end_time - module_start_time))
-echo "Cross Validation completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/cross_validation.log"
+# 检查日志文件是否存在以及是否包含关键字
+LOG_FILE="${OUTPUT_DIR}/Log/cross_validation.log"
+KEYWORD="Cross Validation completed"
+
+if [ -f "$LOG_FILE" ] && grep -q "$KEYWORD" "$LOG_FILE"; then
+    echo "Cross Validation module already completed, skipping..."
+else
+    module_start_time=$(date +%s)
+    # 根据 CONCENTRATION_TYPE 进行不同的处理
+    if [ "$CONCENTRATION_TYPE" == "non-concentration" ]; then
+        cross_validation_module.sh --non-concentration > "$LOG_FILE" 2>&1
+    else
+        cross_validation_module.sh --concentration > "$LOG_FILE" 2>&1
+    fi
+    module_end_time=$(date +%s)
+    module_runtime=$((module_end_time - module_start_time))
+    echo "Cross Validation completed in ${module_runtime} seconds." >> "$LOG_FILE"
+fi
+
 
 #Binning and merge module
 echo "Starting Binning and merge module..."
@@ -204,21 +236,37 @@ module_end_time=$(date +%s)
 module_runtime=$((module_end_time - module_start_time))
 echo "Summary completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/summary.log"
 
-#dRep module
+# dRep module
 echo "Starting dRep module..."
-module_start_time=$(date +%s)
-drep_module.sh > "${OUTPUT_DIR}/Log/drep.log" 2>&1
-module_end_time=$(date +%s)
-module_runtime=$((module_end_time - module_start_time))
-echo "dRep completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/drep.log"
+LOG_FILE="${OUTPUT_DIR}/Log/drep.log"
+# 检查日志文件是否存在且包含关键字
+if [ -f "$LOG_FILE" ] && grep -q "Combined fasta files and quality summaries completed." "$LOG_FILE"; then
+  echo "dRep module already completed, skipping..."
+else
+  module_start_time=$(date +%s)
+  # 执行 dRep 模块
+  drep_module.sh > "$LOG_FILE" 2>&1
+  module_end_time=$(date +%s)
+  module_runtime=$((module_end_time - module_start_time))
+  echo "dRep completed in ${module_runtime} seconds." >> "$LOG_FILE"
+fi
 
 #TPM caculate module
-echo "Starting TPM caculate module..."
-module_start_time=$(date +%s)
-TPM_caculate_Module.sh > "${OUTPUT_DIR}/Log/TPM_caculate.log" 2>&1
-module_end_time=$(date +%s)
-module_runtime=$((module_end_time - module_start_time))
-echo "TPM caculate completed in ${module_runtime} seconds." >> "${OUTPUT_DIR}/Log/TPM_caculate.log"
+LOG_FILE="${OUTPUT_DIR}/Log/TPM_caculate.log"
+# 检查日志文件是否存在，并且是否包含 "TPM calculation completed successfully."
+if [ -f "$LOG_FILE" ] && grep -q "TPM calculation completed successfully." "$LOG_FILE"; then
+    echo "TPM calculation already completed, skipping..."
+else
+    echo "Starting TPM calculate module..."
+    module_start_time=$(date +%s)
+    # 执行TPM计算模块并将日志输出到文件
+    TPM_caculate_Module.sh > "$LOG_FILE" 2>&1
+    module_end_time=$(date +%s)
+    module_runtime=$((module_end_time - module_start_time))
+    # 将运行时间追加到日志文件中
+    echo "TPM calculate completed in ${module_runtime} seconds." >> "$LOG_FILE"
+fi
+
 
 #DRAM module
 echo "Starting DRAM module..."
